### ISSUE TITLE
Attempt to invoke virtual method 'boolean android.database.sqlite.SQLiteDatabase.inTransaction()' on a null object reference at MirakelInternalContentProvider.java:441

### ISSUE THREAD

**Issue by muelli** [MirakelX/mirakel-android#615]
That's the 3.0 release from Fdroid:

```
D/ACRA    (15938): ACRA is enabled for de.azapps.mirakelandroid, initializing...
D/ACRA    (15938): Using default Report Fields
D/ACRA    (15938): Looking for error files in /data/data/de.azapps.mirakelandroid/files
D/ACRA    (15938): Looking for error files in /data/data/de.azapps.mirakelandroid/files
E/ACRA    (15938): ACRA caught a NullPointerException for de.azapps.mirakelandroid
E/ACRA    (15938): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.database.sqlite.SQLiteDatabase.inTransaction()' on a null object reference
E/ACRA    (15938): 	at de.azapps.mirakel.model.MirakelInternalContentProvider.withTransaction(MirakelInternalContentProvider.java:441)
E/ACRA    (15938): 	at de.azapps.mirakel.model.task.Task.unsafeSave(Task.java:655)
E/ACRA    (15938): 	at de.azapps.mirakel.model.task.Task.save(Task.java:593)
E/ACRA    (15938): 	at de.azapps.mirakel.model.task.Task.save(Task.java:588)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.model.TaskWarriorTaskSerializer.serialize(TaskWarriorTaskSerializer.java:116)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.model.TaskWarriorTaskSerializer.serialize(TaskWarriorTaskSerializer.java:51)
E/ACRA    (15938): 	at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70)
E/ACRA    (15938): 	at com.google.gson.Gson.toJson(Gson.java:593)
E/ACRA    (15938): 	at com.google.gson.Gson.toJson(Gson.java:572)
E/ACRA    (15938): 	at com.google.gson.Gson.toJson(Gson.java:527)
E/ACRA    (15938): 	at com.google.gson.Gson.toJson(Gson.java:507)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.TaskWarriorSync.taskToJson(TaskWarriorSync.java:571)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.TaskWarriorSync.sync(TaskWarriorSync.java:536)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.services.SyncAdapter.onPerformSync(SyncAdapter.java:116)
E/ACRA    (15938): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
E/ACRA    (15938): Not adding buildConfig to log. Class Not found : de.azapps.mirakel.BuildConfig. Please configure 'buildConfigClass' in your ACRA config
E/ACRA    (15938): de.azapps.mirakelandroid fatal error : Attempt to invoke virtual method 'boolean android.database.sqlite.SQLiteDatabase.inTransaction()' on a null object reference
E/ACRA    (15938): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.database.sqlite.SQLiteDatabase.inTransaction()' on a null object reference
E/ACRA    (15938): 	at de.azapps.mirakel.model.MirakelInternalContentProvider.withTransaction(MirakelInternalContentProvider.java:441)
E/ACRA    (15938): 	at de.azapps.mirakel.model.task.Task.unsafeSave(Task.java:655)
E/ACRA    (15938): 	at de.azapps.mirakel.model.task.Task.save(Task.java:593)
E/ACRA    (15938): 	at de.azapps.mirakel.model.task.Task.save(Task.java:588)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.model.TaskWarriorTaskSerializer.serialize(TaskWarriorTaskSerializer.java:116)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.model.TaskWarriorTaskSerializer.serialize(TaskWarriorTaskSerializer.java:51)
E/ACRA    (15938): 	at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70)
E/ACRA    (15938): 	at com.google.gson.Gson.toJson(Gson.java:593)
E/ACRA    (15938): 	at com.google.gson.Gson.toJson(Gson.java:572)
E/ACRA    (15938): 	at com.google.gson.Gson.toJson(Gson.java:527)
E/ACRA    (15938): 	at com.google.gson.Gson.toJson(Gson.java:507)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.TaskWarriorSync.taskToJson(TaskWarriorSync.java:571)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.TaskWarriorSync.sync(TaskWarriorSync.java:536)
E/ACRA    (15938): 	at de.azapps.mirakel.sync.taskwarrior.services.SyncAdapter.onPerformSync(SyncAdapter.java:116)
E/ACRA    (15938): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

It seems as if this has already been mentioned here: https://github.com/MirakelX/mirakel-android/issues/601#issuecomment-160266614 but I created a new bug because the other bug's title is not very specific.

**Comment by weiznich** [comment]
This is causing #601. So I will close this in favour of the other issue.
